# Generated by Django 3.0.3 on 2020-09-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0002_auto_20200914_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='stock',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='market',
            new_name='index',
        ),
        migrations.AddField(
            model_name='stocks',
            name='abs_delta',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='abs_perc',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='volume',
            field=models.IntegerField(default=None),
        ),
    ]
