# Generated by Django 3.0.3 on 2020-09-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0003_auto_20200915_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('AI_version', models.FloatField(null=True)),
            ],
        ),
    ]
