# Generated by Django 3.0.3 on 2020-09-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0004_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default=None, max_length=100)),
                ('period_begin', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('pattern', models.CharField(default=None, max_length=200)),
                ('observation', models.TextField()),
                ('relevance', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='stocks',
            name='abs_delta',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='abs_perc',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
