# Generated by Django 3.0.3 on 2020-10-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0010_auto_20201006_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
