# Generated by Django 3.0.3 on 2020-10-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0011_delete_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('is_view_only', 'user_is_view_only'),),
            },
        ),
    ]
