# Generated by Django 3.0.3 on 2020-10-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0012_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'permissions': (('view_only', 'user_view_only'),)},
        ),
    ]
