# Generated by Django 3.0.3 on 2020-10-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0013_auto_20201006_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
    ]
