# Generated by Django 3.0.3 on 2020-10-28 11:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0016_observations_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
