# Generated by Django 3.0.3 on 2020-11-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0017_articles_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image_file',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
