# Generated by Django 3.0.3 on 2020-11-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0019_auto_20201105_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='image_file',
            new_name='top_image',
        ),
    ]
