# Generated by Django 3.0.3 on 2020-11-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0023_auto_20201105_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
