# Generated by Django 3.0.3 on 2020-11-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0024_remove_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
