# Generated by Django 3.0.3 on 2020-11-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0025_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='observations',
            name='abs_change',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='observations',
            name='perc_change',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='observations',
            name='sector',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
