# Generated by Django 3.0.3 on 2020-11-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0026_auto_20201118_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='observations',
            name='indexx',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
